name: CI on demand

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "select environment to run"
        required: true
        default: "qa"
        type: choice
        options:
          - qa
          - dev
      browser:
        description: "select browser to run"
        required: true
        default: "chrome"
        type: choice
        options:
          - chrome
          - firefox
      artifacts:
        description: "Allure report"
        required: false
        type: boolean

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  runTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"
          cache: "npm"
      - name: Install
        run: npm ci --no-fund --no-audit
      - name: Test
        run: npx wdio --env ${{ github.event.inputs.environment }} --browser ${{ github.event.inputs.browser }}
      - if: github.event.inputs.artifacts == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./reports/allure/allure-report
